direction: out
domain_id: 0
pdu_def_path: config/sample/comm/storage_example/pdudef.json
cache: config/sample/cache/buffer.json
zenoh:
  endpoint: tcp/127.0.0.1:7447
rmw_zenoh_graph:
  enabled: true
  node_namespace: /
  enclave: "%"
  session_id: auto
  node_id: 0
  qos: default
mappings:
  - endpoint:
      robot: StorageDemo
      pdu: sample_state
      direction: out
    ros2:
      topic: /sample_state
      message_type: std_msgs/msg/UInt64
